DM-48106: Update alert packet for renaming of dipole classification flags
lsst/alert_packet pull request #44
Opened 2024-12-17 21:15 UTC by abudlong

2024-12-26 19:56 UTC, andy-slac approved these changes
Looks good to me, one question. This is clearly beyond my expertise, maybe asks someone else to review it?

2024-12-26 19:56 UTC, andy-slac commented on python/lsst/alert/packet/schema/7/2/sample_data/generate.py
> +schema = packet.SchemaRegistry.from_filesystem(schema_root="lsst.v7_1.alert").get_by_version("7.1")
Should these be `lsst.v7_2.alert` and `7.2`? Probably the failing tests may be fixed by updating versions here and regenerating `fakeAlert`?

2025-01-10 22:54 UTC, bsmartradio requested changes
This looks good and I know it passes locally, but wait until the other changes get merged first so we can see the unit tests pass here. Once everything passes here we can merge and I'll make the changes needed in Phalanx to close this out.

2025-01-13 22:14 UTC, bsmartradio approved these changes

2025-01-13 22:15 UTC, merged